        <div id="footer">
            <div class="container">
                <footer>
                    <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div>
        </div>
        <!-- Scripts -->
        <?php echo $this->headScript() ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>