<?= $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?= $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false)?>

<?=
$this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<?=
$this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
    ->prependStylesheet($this->basePath() . '/css/style.css')
    ->prependStylesheet($this->basePath() . '/css/sticky-footer.css')
    ->prependStylesheet($this->basePath() . '/components/bootstrap/dist/css/bootstrap.min.css')
    ->prependStylesheet($this->basePath() . '/components/bootstrap/dist/css/bootstrap-theme.min.css')
    ->prependStylesheet($this->basePath() . '/components/font-awesome/css/font-awesome.min.css')
?>

<?=
$this->headScript()
    ->prependFile($this->basePath() . '/components/bootstrap/dist/js/bootstrap.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', [
        'conditional' => 'lt IE 9'
    ])
    ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', [
        'conditional' => 'lt IE 9'
    ]);
?>

</head>