<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'user/index/index'  => __DIR__ . '/view/user/index/index.phtml',
    'user/index/create' => __DIR__ . '/view/user/index/registration.phtml',
    'user/index/login'  => __DIR__ . '/view/user/index/login.phtml',
    'user/index/update' => __DIR__ . '/view/user/index/update.phtml',
);
