<div class="page-header">
    <h1><?php echo $this->translate('Restore password') ?></h1>
</div>

<?php
$this->form->prepare();

// Set the method attribute for the form
$this->form->setAttribute('class', 'form-horizontal');
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
/* @var $form \User\Form\UserForm */
$form = $this->form;
echo $this->form()->openTag($this->form);
?>

<div class="form-group">
    <?php
    /* @var $identity \User\Form\IdentifierFieldset */
    /* @var $identifier \Zend\Form\Element\Text */
    $identity = $this->form->get('identity');
    $identifier = $identity->get('identifier');
    $identifier->setLabelAttributes([
        'class' => 'col-sm-2 control-label'
    ]);
    $identifier->setAttributes([
        'class' => 'form-control'
    ]);
    echo $this->formLabel($identifier);
    echo '<div class="col-sm-10">';
    echo $this->formInput($identifier);
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="bs-callout bs-callout-danger">')
        ->setMessageCloseString('</div>')
        ->render($identifier);
    echo '</div>';
    ?>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        /* @var $element \Zend\Form\Element\Button */
        $element = $this->form->get('send');
        $element->setAttributes([
            'class' => 'btn btn-primary'
        ]);
        echo $this->formElement($element);
        ?>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>