<?php
echo $this->navigation('navigation')
    ->breadcrumbs()
    ->setPartial('partials/breadcrumbs.phtml')
    ->render();
?>

<div class="page-header">
	<h1>Login user</h1>
</div>

<?php
    $form->prepare();

    // Set the method attribute for the form
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');

    // Get the form label plugin
    $formLabel = $this->plugin('formLabel');

    echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?php
    /* @var $element \Zend\Form\Element\Text */
    $element = $form->get('email');
    $element->setLabelAttributes(array(
        'class' => 'col-sm-2 control-label'
    ));
    $element->setAttributes(array(
        'class' => 'form-control'
    ));
    echo $this->formLabel($element);
    echo '<div class="col-sm-10">';
    echo $this->formInput($element);
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="bs-callout bs-callout-danger">')
        ->setMessageCloseString('</div>')
        ->render($element);
    echo '</div>';
    ?>
</div>

<div class="form-group">
    <?php
    /* @var $element \Zend\Form\Element\Password */
    $element = $form->get('password');
    $element->setLabelAttributes(array(
        'class' => 'col-sm-2 control-label'
    ));
    $element->setAttributes(array(
        'class' => 'form-control'
    ));
    echo $this->formLabel($element);
    echo '<div class="col-sm-10">';
    echo $this->formPassword($element);
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="bs-callout bs-callout-danger">')
        ->setMessageCloseString('</div>')
        ->render($element);
    echo '</div>';
    ?>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
        <?php
        /* @var $element \Zend\Form\Element\Button */
        $element = $form->get('send');
        $element->setAttributes(array(
            'class' => 'btn btn-primary'
        ));
        echo $this->formElement($element);
        ?>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>