<div class="page-header">
    <h1><?php echo $this->translate('Change password') ?></h1>
</div>

<?php
$this->form->prepare();

// Set the method attribute for the form
$this->form->setAttribute('class', 'form-horizontal');
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
/* @var $hashElement \Zend\Form\Element\Hidden */
$hashElement = $this->form->get('restore_hash');
$hashElement->setValue($this->hash);

echo $this->form()->openTag($this->form);
echo $this->formHidden($hashElement);
?>

<div class="form-group">
    <?php
    /* @var $credential \Zend\Form\Element\Password */
    $credential = $this->form->get('password');
    $credential->setLabelAttributes([
        'class' => 'col-sm-2 control-label'
    ]);
    $credential->setAttributes([
        'class' => 'form-control'
    ]);
    echo $this->formLabel($credential);
    echo '<div class="col-sm-10" id="field-password">';
    echo $this->formPassword($credential);
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="bs-callout bs-callout-danger">')
        ->setMessageCloseString('</div>')
        ->render($credential);
    echo '</div>';
    ?>
</div>

<div class="form-group">
    <?php
    /* @var $credential \Zend\Form\Element\Password */
    $credential = $this->form->get('identical');
    $credential->setLabelAttributes([
        'class' => 'col-sm-2 control-label'
    ]);
    $credential->setAttributes([
        'class' => 'form-control'
    ]);
    echo $this->formLabel($credential);
    echo '<div class="col-sm-10" id="field-identical">';
    echo $this->formPassword($credential);
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="bs-callout bs-callout-danger">')
        ->setMessageCloseString('</div>')
        ->render($credential);
    echo '</div>';
    ?>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        /* @var $element \Zend\Form\Element\Button */
        $element = $this->form->get('send');
        $element->setAttributes([
            'class' => 'btn btn-primary'
        ]);
        echo $this->formElement($element);
        ?>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>