<div class="col-md-4">
    <blockquote>
        <p><h1><?php echo $this->translate('Sign In'); ?></h1></p>
    </blockquote>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <?php $form->get('identity')->setAttribute('class', 'form-control') ?>
        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <?php $form->get('credential')->setAttribute('class', 'form-control') ?>
        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <?php $form->get('submit')->setAttribute('class', 'btn btn-primary') ?>
        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>

</div>